title: Data Analysis and Networking Lab.
email: danlab5502@gmail.com
description: >-
baseurl: ''
url: ''
github_username: https://github.com/Dan-Lab-5502
theme: minima
plugins:
  - jekyll-feed
navbar-links:
  Category:
    - TroubleShooting: "/category/troubleshooting"
    - Study: "/category/study"
