title: Data Analysis and Networking Lab.
email: danlab5502@gmail.com
description: >-
  DAN lab is established by prof. Hyunhee Park (assistant professor of the department of Information and Communication at Myongji University). 
  Major research topics are big data analysis, protocol design, and information security on the Internet of Things (IoT) environment and various operating systems. 
baseurl: ''
url: ''
twitter_username: jekyllrb
github_username: jekyll
theme: minima
plugins:
  - jekyll-feed
